log_level = "Error"

[[temp_matrix]]
temp = 4.0
speed = 4.0

[[temp_matrix]]
temp = 30.0
speed = 33.0

[[temp_matrix]]
temp = 45.0
speed = 50.0

[[temp_matrix]]
temp = 60.0
speed = 66.0

[[temp_matrix]]
temp = 65.0
speed = 69.0

[[temp_matrix]]
temp = 70.0
speed = 75.0

[[temp_matrix]]
temp = 95.0
speed = 89.0

[[temp_matrix]]
temp = 80.0
speed = 100.0
