log_level = "Trace"
temp_input = "temp1_input"
update_rate = 100

[[temp_matrix]]
temp = 4.0
speed = 4.0

[[temp_matrix]]
temp = 30.0
speed = 33.0

[[temp_matrix]]
temp = 45.0
speed = 50.0

[[temp_matrix]]
temp = 60.0
speed = 66.0

[[temp_matrix]]
temp = 65.0
speed = 69.0

[[temp_matrix]]
temp = 70.0
speed = 75.0

[[temp_matrix]]
temp = 75.0
speed = 89.0

[[temp_matrix]]
temp = 80.0
speed = 100.0

[[usage_matrix]]
usage = 30.0
speed = 34.0

[[usage_matrix]]
usage = 600.0
speed = 50.0

[[usage_matrix]]
usage = 85.0
speed = 60.0

[[usage_matrix]]
usage = 100.0
speed = 100.0
